[package]
name = "verus_zfunc"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
test = true
doctest = false

[[bin]]
name = "run_test"
path = "src/bin/run_test.rs"
required-features = ["run-test-bin"]

[dependencies]
secrecy.workspace = true
hex = "0.4.3"
rand_core = { version = "0.6.4", features = ["getrandom"] }
rand = "0.8.5"
jubjub.workspace = true
blake2b_simd.workspace = true
getrandom = { version = "0.2.16", features = ["js"] }
chacha20poly1305 = { version = "0.10.1", features = ["heapless"] }
sha2 = "0.10.8"
anyhow = "1.0"
bech32 = "0.9"
ripemd.workspace = true
group = "0.13.0"

zcash_keys = { workspace = true, features = ["sapling"] }
zcash_note_encryption.workspace = true
zcash_primitives.workspace = true
orchard = { workspace = true, optional = true }
sapling.workspace = true
bs58.workspace = true

[features]
run-test-bin = []
